# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoCurrency_name', models.CharField(max_length=20)),
                ('cryptoCurrency_symbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCurrency_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcet_cap', models.DecimalField(decimal_places=2, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=16)),
                ('volum', models.DecimalField(decimal_places=2, max_digits=16)),
                ('h1', models.DecimalField(decimal_places=2, max_digits=16)),
                ('h24', models.DecimalField(decimal_places=2, max_digits=16)),
                ('d7', models.DecimalField(decimal_places=2, max_digits=16)),
                ('insert_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cryptoCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='webpage.CryptoCurrency')),
            ],
            options={
                'ordering': ['-insert_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cryptocurrency',
            unique_together=set([('cryptoCurrency_name', 'cryptoCurrency_symbol')]),
        ),
    ]
